language: ruby
rvm:
  - 2.3
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --file-ignore "/mlab_observatory/","/ndt/"
branches:
  only:
  - master
  - gh-pages
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh
